name: Security Checks
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 6 * * 1"
jobs:
  slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { submodules: recursive }
      - uses: crytic/slither-action@v0.4.0
        with:
          target: "src/"
          slither-config: "slither.config.json"
